### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [go-restruct/restruct#42] opened 2020-08-06 23:42 UTC
I found that this project already [supports Go modules](https://github.com/go-restruct/restruct/blob/master/go.mod). But sadly, the [tags](https://github.com/go-restruct/restruct/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/go-restruct/restruct v0.0.0-20191227155143-5734170a48a1
```
Else the mod file shows something like `github.com/go-restruct/restruct v0.0.0-20191227155143-5734170a48a1` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment] 2020-08-06 23:43
@jchv  @neglect-yp  Could you help me review this issue? Thx :p

**Comment by jchv** [comment] 2020-08-07 02:20
SGTM, but there's a little more to it: none of the releases support Go modules.  Restruct hasn't been released in a while in part because there's still a lot of things that would be nice to do for v2 but I have been working on other things. Maybe I can release an alpha of some kind with the current state of the repo.

**Comment by KateGo520** [comment] 2020-08-07 05:57
@jchv A new version v1.2.0-alpha maybe. I think it's a good idea.

**Comment by neglect-yp** [comment] 2020-08-07 05:58
SGTM.

How about re-releasing `v1.1` as `v1.1.0` (stable)?

If you think that 2 same releases confuse users, ignore this comment.

**Comment by KateGo520** [comment] 2020-08-07 06:02
Releasing an alpha of some kind with the current state of the repo sounds better for me than the old version.

**Comment by jchv** [comment] 2020-08-07 06:55
Sure, I can go release a v1.2.0-alpha. I considered releasing v1.1 as v1.1.0, but since it doesn't have a Go module manifest I am unsure if it will work as intended? This really ought to, though.

**Comment by jchv** [comment] 2020-08-07 07:01
v1.2.0-alpha has been pushed. Please let me know if there are any problems.

**Comment by KateGo520** [comment] 2020-08-07 07:12
It works! Thank you!

> $go get github.com/go-restruct/restruct
> go: github.com/go-restruct/restruct upgrade => v1.2.0-alpha
> go: downloading github.com/go-restruct/restruct v1.2.0-alpha

**Comment by jchv** [comment] 2020-08-07 19:36
Great, thanks for letting me know. Closing now.

**Closed by jchv** 2020-08-07 19:36 UTC
